### ISSUE TITLE
Handler must be a function

### ISSUE THREAD

**Issue by coolacid** [SupportClass/lfg-streamtip#2]
Error in logs: 

```
error: [nodecg/lib/server/extensions] Failed to mount lfg-streamtip extension: Error: argument "handler" must be a function, but you provided a(n) undefined
    at NodeCG.__dirname.NodeCG.socket.on.socket.on.io.on.NodeCG.listenFor (/home/node/nodecg/lib/api.js:224:9)
    at module.exports (/home/node/nodecg/bundles/lfg-streamtip/extension.js:54:12)
    at _loadExtension (/home/node/nodecg/lib/server/extensions.js:104:37)
    at EventEmitter.<anonymous> (/home/node/nodecg/lib/server/extensions.js:34:6)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at /home/node/nodecg/node_modules/@nodecg/bundle-manager/index.js:139:12
    at _fulfilled (/home/node/nodecg/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/node/nodecg/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/node/nodecg/node_modules/q/q.js:796:13)
```

**Comment by Lange** [comment]
was fixed by 87e15d110076979e6af5e582387665f6e635ddb4
